// The Windows C++/WinRT coroutine workaround must not outlive its need.
//
// WHY THIS EXISTS: `windows/CMakeLists.txt` raises two plugins to C++20 (and
// silences one deprecation) so that `winrt/base.h` stops falling back to
// `<experimental/coroutine>`, which MSVC 14.51 turns into a hard STL1011
// error. Both halves are stopgaps waiting on somebody else's release:
//
//   * audioplayers_windows shipped the very same fix in 4.4.1. We cannot take
//     it, because 4.4.1 requires Flutter >= 3.44 while CI pins 3.41.9 — so the
//     override has to stay until the Flutter pin moves.
//   * permission_handler_windows is still unfixed at its latest release, and
//     the escape hatch is a define Microsoft says will stop working.
//
// Both facts were true on the day they were written and will quietly stop
// being true. A comment cannot notice that; nobody re-reads a workaround that
// is working. So this test names the exact artifacts the workaround was
// verified against and fails on anything else — which is the moment to delete a
// line rather than carry it for another year.
//
// Three things it deliberately does, each because the first version of it did
// not and a review caught the hole (codex 2026-09-28):
//
//   * It gates the ARTIFACT, not a numeric prefix: a prerelease, a `+1`
//     rebuild, a git/path replacement or a different hosted repository is a
//     different set of sources than the one somebody read, so the lock's own
//     sha256 and url are checked too.
//   * It reads only the EXECUTABLE part of the CMake block, with comments
//     stripped. The comment above the block names every symbol the block uses,
//     so a file-wide — or even a body-wide — text search stays green after the
//     real call is deleted or commented out.
//   * It fails when the loop still names a package the app no longer depends
//     on. CMake cannot: a package that left FLUTTER_PLUGIN_LIST must not break
//     the build. So the override would otherwise sit there as dead code for
//     ever, with every test skipping it.
//
// It reads `pubspec.lock` (tracked, and regenerated by `flutter pub get`
// before the test job runs), so it gates the versions CI actually builds, not
// the constraints in `pubspec.yaml`. It needs no Windows host.

import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

/// What somebody actually inspected for one package.
class Reviewed {
  const Reviewed({required this.artifacts, required this.fixedIn});

  /// Version -> the `sha256` a lockfile records for the archive that was read.
  /// For a release that has never been locked here, that is pub.dev's
  /// `archive_sha256`, which is the same value. A null sha would mean the
  /// version is accepted without a content check, so it is only for a release
  /// whose hash genuinely cannot be obtained -- prefer pinning.
  final Map<String, String?> artifacts;

  /// The first release that carries the fix upstream, so the failure message
  /// can say "delete the override" rather than "go and look". Null when
  /// upstream has not fixed it in any release yet.
  final String? fixedIn;
}

const reviewed = <String, Reviewed>{
  // 3.1.0 requests no standard of its own, so APPLY_STANDARD_SETTINGS gives it
  // C++17 and winrt/base.h takes the deprecated path. 4.4.1 sets cxx_std_20
  // itself; it needs Flutter >= 3.44, and 4.3.1 (the newest our pin allows)
  // does NOT carry the fix.
  'audioplayers_windows': Reviewed(
    artifacts: {
      '3.1.0':
          '9536812c9103563644ada2ef45ae523806b0745f7a78e89d1b5fb1951de90e1a',
    },
    fixedIn: '4.4.1',
  ),
  // 0.2.1 (locked) and 0.2.2 (latest release) both request C++20 already and
  // both still reach the deprecated header, so the define is load-bearing.
  // Upstream: flutter-permission-handler issue #1534.
  'permission_handler_windows': Reviewed(
    artifacts: {
      '0.2.1':
          '1a790728016f79a41216d88672dbc5df30e686e811ad4e698bfc51f76ad91f1e',
      // Not locked here, so the hash comes from pub.dev's `archive_sha256`,
      // which is the value a lockfile records (checked against 0.2.1, which
      // matches ours exactly).
      '0.2.2':
          'caeae01858a0a7d2df67a445ac98e1ad95e55a0e77c73044f4e9b1c8c2289cbd',
    },
    fixedIn: null,
  ),
};

/// One package's resolved identity in a `pubspec.lock`.
typedef LockedEntry = ({
  String? version,
  String? source,
  String? sha256,
  String? url,
});

/// [package]'s entry, or null when the package is not in the resolution at all.
LockedEntry? lockedEntry(String lock, String package) {
  final entry = RegExp(
    '^  ${RegExp.escape(package)}:\$',
    multiLine: true,
  ).firstMatch(lock);
  if (entry == null) return null;
  // Stop at the next package entry, so a field this one lacks cannot be
  // borrowed from the package that follows it.
  final rest = lock.substring(entry.end);
  final nextEntry = RegExp(r'^  [a-z0-9_]+:$', multiLine: true).firstMatch(rest);
  final block = nextEntry == null ? rest : rest.substring(0, nextEntry.start);
  String? field(String name, int indent) =>
      RegExp('^${' ' * indent}$name: "?([^"\n]+)"?\$', multiLine: true)
          .firstMatch(block)
          ?.group(1);
  return (
    version: field('version', 4),
    source: field('source', 4),
    sha256: field('sha256', 6),
    url: field('url', 6),
  );
}

/// A HINT for the failure message only — never the gate. -1, 0 or 1 comparing
/// the numeric release parts; a prerelease sorts before its release, the way
/// SemVer orders them.
int compareReleases(String a, String b) {
  List<int> release(String v) => v
      .split(RegExp(r'[-+]'))
      .first
      .split('.')
      .map((s) => int.tryParse(s) ?? 0)
      .toList();
  final pa = release(a);
  final pb = release(b);
  for (var i = 0; i < (pa.length > pb.length ? pa.length : pb.length); i++) {
    final x = i < pa.length ? pa[i] : 0;
    final y = i < pb.length ? pb[i] : 0;
    if (x != y) return x < y ? -1 : 1;
  }
  final preA = a.contains('-');
  final preB = b.contains('-');
  if (preA != preB) return preA ? -1 : 1;
  return 0;
}

/// Everything after the first `#` that is not inside a double-quoted string,
/// which is where a CMake line comment starts. A `#` inside a string is data.
String withoutLineComment(String line) {
  var inQuotes = false;
  for (var i = 0; i < line.length; i++) {
    final c = line[i];
    if (c == '"') {
      // Escaped only when an ODD number of backslashes precedes it: in `"a\\"`
      // the backslash is itself escaped and the quote DOES close the string, so
      // counting just one would keep reading a comment as code
      // (codex 2026-09-28).
      var backslashes = 0;
      for (var j = i - 1; j >= 0 && line[j] == r'\'; j--) {
        backslashes++;
      }
      if (backslashes.isEven) inQuotes = !inQuotes;
    } else if (c == '#' && !inQuotes) {
      return line.substring(0, i);
    }
  }
  return line;
}

/// The `foreach(winrt_plugin ...)` block of `windows/CMakeLists.txt` with every
/// comment removed, i.e. only what CMake will actually execute.
///
/// Every comment form goes, because each one in turn hid a disabled call from
/// an earlier version of this test (codex 2026-09-28): a whole comment LINE, an
/// INLINE `#` after real code (`message(...) # target_compile_features(...)`
/// applies no C++20 feature at all), and CMake's bracket comment `#[[ ... ]]`
/// with any number of `=` in the brackets, whose interior the compiler never
/// sees.
({String packages, String code})? winrtLoop(String cmake) {
  final header = RegExp(r'foreach\(winrt_plugin ([^\)]*)\)').firstMatch(cmake);
  if (header == null) return null;
  final endIndex = cmake.indexOf('endforeach()', header.end);
  if (endIndex < 0) return null;
  final code = cmake
      .substring(header.end, endIndex)
      .replaceAll(RegExp(r'#\[(=*)\[[\s\S]*?\]\1\]'), '')
      .split('\n')
      .map(withoutLineComment)
      .join('\n');
  return (packages: header.group(1)!.trim(), code: code);
}

/// The packages `windows/flutter/generated_plugins.cmake` will actually build.
/// A package can stay in `pubspec.lock` and yet leave this list (its Windows
/// implementation is dropped, or it stops being a plugin) -- and CMake has to
/// skip such a package rather than fail, so nothing else would notice the
/// override had become dead code (codex 2026-09-28).
Set<String> generatedWindowsPlugins(String generated) {
  final block =
      RegExp(r'list\(APPEND FLUTTER_PLUGIN_LIST([^)]*)\)').firstMatch(generated);
  if (block == null) return const <String>{};
  return block
      .group(1)!
      .split(RegExp(r'\s+'))
      .where((s) => s.isNotEmpty)
      .toSet();
}

void main() {
  const lockPath = 'pubspec.lock';
  const cmakePath = 'windows/CMakeLists.txt';
  const generatedPath = 'windows/flutter/generated_plugins.cmake';

  late String lock;
  late String cmake;
  late String generated;

  setUpAll(() async {
    lock = await File(lockPath).readAsString();
    cmake = await File(cmakePath).readAsString();
    generated = await File(generatedPath).readAsString();
  });

  for (final entry in reviewed.entries) {
    final package = entry.key;
    final expected = entry.value;

    test('$package is still the artifact the workaround was verified against',
        () {
      final locked = lockedEntry(lock, package);
      if (locked == null) {
        // The app dropped the dependency. Nothing to verify here; the
        // dead-override test below is what notices.
        expect(lock, isNot(contains('  $package:')));
        return;
      }
      expect(locked.version, isNotNull,
          reason: '$package has an entry in $lockPath with no version, so this '
              'gate cannot tell which sources CI builds');
      expect(locked.source, 'hosted',
          reason: '$package resolves from "${locked.source}", not pub.dev. A '
              'git or path replacement can carry any version number, so the '
              'workaround in $cmakePath has to be re-verified against those '
              'sources.');
      expect(locked.url, 'https://pub.dev',
          reason: '$package comes from "${locked.url}", which is not the '
              'repository whose sources were read');

      final version = locked.version!;
      final fixedIn = expected.fixedIn;
      final hint = fixedIn != null && compareReleases(version, fixedIn) >= 0
          ? 'That is $fixedIn or newer, and $fixedIn sets cxx_std_20 on its own '
              'plugin target, so the override for $package in $cmakePath can '
              'most likely be deleted outright.'
          : 'Read its windows/ sources: if it no longer reaches '
              '<experimental/coroutine>, drop it from the winrt_plugin loop in '
              '$cmakePath; otherwise add $version to the reviewed set here.';
      expect(expected.artifacts.keys, contains(version),
          reason: '$package is locked at $version, which nobody has checked '
              'against this workaround (reviewed: '
              '${expected.artifacts.keys.join(", ")}). $hint');

      final pinned = expected.artifacts[version];
      if (pinned != null) {
        expect(locked.sha256, pinned,
            reason: '$package $version does not have the contents that were '
                'read: the lockfile records ${locked.sha256}. Re-read the '
                'sources and update the pin here.');
      }
    });
  }

  test('the loop that runs still applies the fix to every package that needs it',
      () {
    final loop = winrtLoop(cmake);
    expect(loop, isNotNull,
        reason: 'the winrt_plugin loop is gone from $cmakePath; if that is '
            'deliberate, this test has to go with it');
    final covered = loop!.packages.split(RegExp(r'\s+'));

    for (final package in reviewed.keys) {
      if (lockedEntry(lock, package) == null) continue;
      expect(covered, contains(package),
          reason: '$package is still in the resolution but $cmakePath no '
              'longer raises it to C++20');
    }

    // Against the executable text only, so a call that has been deleted OR
    // commented out cannot hide behind the comment that explains it.
    expect(loop.code, contains(r'target_compile_features(${winrt_plugin}_plugin'),
        reason: 'the loop no longer raises the standard for anything');
    expect(loop.code, contains('cxx_std_20'));
    expect(loop.code,
        contains('_SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS'),
        reason: 'permission_handler_windows needs the define as well as C++20');
    expect(loop.code, contains('permission_handler_windows'),
        reason: 'the define must stay scoped to the plugin that needs it');
  });

  test('the loop does not name a package the Windows build no longer has', () {
    // CMake cannot report this: a package that left FLUTTER_PLUGIN_LIST has to
    // be skipped there, or removing a dependency would break the build. So the
    // override would sit as dead code with every other check skipping it.
    final loop = winrtLoop(cmake);
    expect(loop, isNotNull);
    final plugins = generatedWindowsPlugins(generated);
    expect(plugins, isNotEmpty,
        reason: '$generatedPath did not parse, so this gate would watch nothing');
    for (final package in loop!.packages.split(RegExp(r'\s+'))) {
      expect(lockedEntry(lock, package), isNotNull,
          reason: '$cmakePath still raises $package to C++20, but it is not in '
              '$lockPath any more. Remove it from the winrt_plugin loop (and '
              'from the reviewed set in this test).');
      expect(plugins, contains(package),
          reason: '$cmakePath still raises $package to C++20, but $generatedPath '
              'does not build it, so that line is dead. Either the package no '
              'longer has a Windows implementation (remove it from the loop and '
              'from the reviewed set here), or the generated file is stale and '
              'needs a `flutter pub get`.');
    }
  });

  test('a missing plugin target fails the build instead of skipping the fix',
      () {
    // The override is keyed by target name. `if(TARGET ...)` alone would drop
    // it silently on a rename — the failure then surfaces as a compiler error
    // inside winrt/base.h, several layers away from the cause.
    final loop = winrtLoop(cmake);
    expect(loop, isNotNull);
    expect(loop!.code, contains('FATAL_ERROR'),
        reason: 'a package in FLUTTER_PLUGIN_LIST with no matching target must '
            'be a hard error in $cmakePath, not a skip');
    expect(loop.code, contains('IN_LIST FLUTTER_PLUGIN_LIST'),
        reason: 'the guard must key off the generated plugin list, so that a '
            'package the app no longer uses is not mistaken for a rename');
  });

  test('the lock reader and the loop reader both really read something', () {
    // Without this, a format change that makes either reader return null turns
    // the gates above into vacuous passes: each one returns early on null, so
    // the suite would stay green while watching nothing.
    const sample = r'''
packages:
  audioplayers:
    dependency: "direct main"
    description:
      name: audioplayers
      sha256: aaaa
      url: "https://pub.dev"
    source: hosted
    version: "5.2.1"
  audioplayers_windows:
    dependency: transitive
    description:
      name: audioplayers_windows
      sha256: "bbbb"
      url: "https://pub.dev"
    source: hosted
    version: "3.1.0"
  mirrored_package:
    dependency: transitive
    description:
      name: mirrored_package
      sha256: "cccc"
      url: "https://pub.example.com"
    source: hosted
    version: "3.1.0"
  forked_package:
    dependency: transitive
    description:
      path: "."
      ref: main
    source: git
    version: "0.2.1"
  broken_no_version:
    dependency: transitive
  next_package:
    dependency: transitive
    version: "9.9.9"
''';
    expect(lockedEntry(sample, 'audioplayers_windows')?.version, '3.1.0');
    expect(lockedEntry(sample, 'audioplayers_windows')?.source, 'hosted');
    expect(lockedEntry(sample, 'audioplayers_windows')?.sha256, 'bbbb');
    expect(lockedEntry(sample, 'mirrored_package')?.url, 'https://pub.example.com',
        reason: 'a different hosted repository must be recognisable');
    expect(lockedEntry(sample, 'forked_package')?.source, 'git',
        reason: 'a replaced package must be recognisable as not-pub.dev');
    expect(lockedEntry(sample, 'absent_package'), isNull);
    // The entry has no version of its own; it must not inherit the next one.
    expect(lockedEntry(sample, 'broken_no_version')?.version, isNull);

    expect(compareReleases('4.3.1', '4.4.1'), lessThan(0));
    expect(compareReleases('4.4.1', '4.4.1'), 0);
    expect(compareReleases('4.4.2', '4.4.1'), greaterThan(0));
    expect(compareReleases('4.10.0', '4.9.0'), greaterThan(0));
    // A prerelease comes BEFORE its release, so it must not read as "the fix
    // has shipped".
    expect(compareReleases('4.4.1-dev.1', '4.4.1'), lessThan(0));
    expect(compareReleases('4.4.1+1', '4.4.1'), 0);

    // Comments must not count as code, and code must survive the stripping.
    final stripped = winrtLoop('''
foreach(winrt_plugin a b)
  # target_compile_features(commented_out PRIVATE cxx_std_20)
  target_compile_features(\${winrt_plugin}_plugin PRIVATE cxx_std_20)
endforeach()
''');
    expect(stripped!.code, isNot(contains('commented_out')));
    expect(stripped.code, contains(r'target_compile_features(${winrt_plugin}'));

    // An INLINE comment hides the rest of its line from CMake.
    final inline = winrtLoop('''
foreach(winrt_plugin a)
  message(STATUS "disabled") # target_compile_features(inline_out PRIVATE cxx_std_20)
  message(STATUS "a # inside a string is data")
endforeach()
''');
    expect(inline!.code, isNot(contains('inline_out')));
    expect(inline.code, contains('a # inside a string is data'),
        reason: 'a hash inside a quoted string is not a comment');
    expect(withoutLineComment('  target_compile_features(x) # note'),
        '  target_compile_features(x) ');
    expect(withoutLineComment('# whole line'), '');
    expect(withoutLineComment(r'message(STATUS "a\\") # target_compile_features'),
        r'message(STATUS "a\\") ',
        reason: 'an escaped backslash does not escape the quote after it');
    expect(withoutLineComment(r'message(STATUS "a\" # b") # real comment'),
        r'message(STATUS "a\" # b") ',
        reason: 'but an escaped quote does keep the string open');

    // A bracket comment hides its interior from CMake, so it must be invisible
    // here too.
    final bracketed = winrtLoop('''
foreach(winrt_plugin a)
#[==[
  target_compile_features(bracketed_out PRIVATE cxx_std_20)
]==]
  message(STATUS "real")
endforeach()
''');
    expect(bracketed!.code, isNot(contains('bracketed_out')));
    expect(bracketed.code, contains('message(STATUS "real")'));

    expect(generatedWindowsPlugins(generated), contains('audioplayers_windows'),
        reason: 'the generated plugin list reader must really read the list');
    expect(
        generatedWindowsPlugins('list(APPEND FLUTTER_PLUGIN_LIST\n  a\n  b\n)'),
        <String>{'a', 'b'});
    expect(generatedWindowsPlugins('nothing here'), isEmpty);

    // The real files must parse, or every gate above quietly watches nothing.
    for (final package in reviewed.keys) {
      if (!lock.contains('  $package:')) continue;
      expect(lockedEntry(lock, package)?.version, isNotNull,
          reason: '$package is in $lockPath but its version does not parse, so '
              'its gate cannot fire');
    }
    expect(winrtLoop(cmake), isNotNull,
        reason: '$cmakePath no longer parses as a winrt_plugin loop');
  });
}
