import 'dart:typed_data';
import 'dart:ui' as ui;

/// Draws the system-tray / menu-bar icon for each desktop platform's format.
///
/// The artwork comes from `assets/tray/` (generated by
/// `tool/branding/generate_brand_assets.py`); this class only composes the
/// runtime state on top of it:
///
/// - macOS: a *template* image (black + alpha). AppKit tints it for the light
///   or dark menu bar, so it can carry no colour; offline is shown by dimming
///   the glyph, the unread count goes into the status item's title.
/// - Windows: a multi-resolution `.ico`. The tray loads the file with
///   `LoadImage(IMAGE_ICON)` at the DPI's small-icon size (16 px at 100 %,
///   20/24/32/40 px at 125-250 %), which rejects a plain PNG file outright.
/// - Linux: a PNG for the StatusNotifier / AppIndicator host.
///
/// On Windows and Linux the colour icon is desaturated while offline and
/// carries an unread badge in its top-right corner.
class TrayIconRenderer {
  const TrayIconRenderer({
    required this.colorIcon,
    required this.templateIcon,
    required this.badgeColor,
  });

  final ui.Image? colorIcon;
  final ui.Image? templateIcon;
  final ui.Color badgeColor;

  /// macOS draws the status item at 18 pt; 36 px covers Retina.
  static const int macTemplateSize = 36;

  /// Small-icon sizes Windows asks for at 100 / 125 / 150 / 200 / 250 %.
  static const List<int> windowsIcoSizes = [16, 20, 24, 32, 40, 48];

  /// AppIndicator panels draw at 22-24 logical px, 2x on HiDPI.
  static const int linuxPngSize = 64;

  static const double _offlineTemplateOpacity = 0.4;

  /// Badge text for [count] at a [size]-px icon. Below 24 px only one digit
  /// is legible; the tooltip carries the exact number.
  static String badgeLabel(int count, int size) {
    if (count <= 0) return '';
    if (size < 24) return count > 9 ? '9+' : '$count';
    return count > 99 ? '99+' : '$count';
  }

  Future<Uint8List> macTemplatePng({required bool online}) async {
    const size = macTemplateSize;
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder);
    final rect = ui.Rect.fromLTWH(0, 0, size.toDouble(), size.toDouble());
    final paint = ui.Paint()
      ..filterQuality = ui.FilterQuality.high
      ..color = ui.Color.fromRGBO(
          0, 0, 0, online ? 1.0 : _offlineTemplateOpacity);
    final image = templateIcon;
    if (image != null) {
      canvas.drawImageRect(image, _bounds(image), rect, paint);
    } else {
      canvas.drawRRect(
          ui.RRect.fromRectAndRadius(rect.deflate(4), const ui.Radius.circular(6)),
          paint);
    }
    return _encodePng(recorder, size);
  }

  Future<Uint8List> linuxPng({required int count, required bool online}) =>
      colorPng(size: linuxPngSize, count: count, online: online);

  Future<Uint8List> windowsIco({required int count, required bool online}) async {
    final entries = <Uint8List>[];
    for (final size in windowsIcoSizes) {
      entries.add(await colorPng(size: size, count: count, online: online));
    }
    return encodeIco(entries, windowsIcoSizes);
  }

  Future<Uint8List> colorPng({
    required int size,
    required int count,
    required bool online,
  }) async {
    final s = size.toDouble();
    final recorder = ui.PictureRecorder();
    final canvas = ui.Canvas(recorder);
    final rect = ui.Rect.fromLTWH(0, 0, s, s);
    final paint = ui.Paint()..filterQuality = ui.FilterQuality.high;
    if (!online) paint.colorFilter = _greyscale;
    final image = colorIcon;
    if (image != null) {
      canvas.drawImageRect(image, _bounds(image), rect, paint);
    } else {
      paint.color = const ui.Color(0xFF1F4A7C);
      canvas.drawRRect(
          ui.RRect.fromRectAndRadius(rect, ui.Radius.circular(s * 0.2)), paint);
    }
    final label = badgeLabel(count, size);
    if (label.isNotEmpty) _drawBadge(canvas, s, label);
    return _encodePng(recorder, size);
  }

  void _drawBadge(ui.Canvas canvas, double size, String label) {
    // Half the icon at normal sizes; at 16-20 px that would be an 8 px blob
    // with an unreadable digit, so small icons give the badge more room.
    final height = (size * (size < 24 ? 0.625 : 0.5)).roundToDouble();
    final paragraph = _label(label, height * 0.72);
    final width = (paragraph.maxIntrinsicWidth + height * 0.3)
        .clamp(height, size)
        .roundToDouble();
    final badge = ui.RRect.fromRectAndRadius(
      ui.Rect.fromLTWH(size - width, 0, width, height),
      ui.Radius.circular(height / 2),
    );
    // Punch a ring out of the icon so the badge reads on any artwork.
    final ring = (size / 16).clamp(1.0, 3.0);
    canvas.drawRRect(
        badge.inflate(ring), ui.Paint()..blendMode = ui.BlendMode.clear);
    canvas.drawRRect(badge, ui.Paint()..color = badgeColor);
    paragraph.layout(ui.ParagraphConstraints(width: width));
    canvas.drawParagraph(
      paragraph,
      ui.Offset(size - width, (height - paragraph.height) / 2),
    );
  }

  ui.Paragraph _label(String text, double fontSize) {
    final builder = ui.ParagraphBuilder(ui.ParagraphStyle(
      textAlign: ui.TextAlign.center,
      fontSize: fontSize,
      height: 1.0,
      maxLines: 1,
    ))
      ..pushStyle(ui.TextStyle(
        color: const ui.Color(0xFFFFFFFF),
        fontWeight: ui.FontWeight.w700,
      ))
      ..addText(text);
    return builder.build()
      ..layout(const ui.ParagraphConstraints(width: double.infinity));
  }

  static const ui.ColorFilter _greyscale = ui.ColorFilter.matrix(<double>[
    0.2126, 0.7152, 0.0722, 0, 0, //
    0.2126, 0.7152, 0.0722, 0, 0, //
    0.2126, 0.7152, 0.0722, 0, 0, //
    0, 0, 0, 0.75, 0, //
  ]);

  static ui.Rect _bounds(ui.Image image) => ui.Rect.fromLTWH(
      0, 0, image.width.toDouble(), image.height.toDouble());

  static Future<Uint8List> _encodePng(
      ui.PictureRecorder recorder, int size) async {
    final picture = recorder.endRecording();
    final image = await picture.toImage(size, size);
    picture.dispose();
    final data = await image.toByteData(format: ui.ImageByteFormat.png);
    image.dispose();
    return data!.buffer.asUint8List();
  }

  /// Packs square PNG images into an ICO container (PNG-compressed entries,
  /// supported since Windows Vista). [sizes] gives each entry's edge length.
  static Uint8List encodeIco(List<Uint8List> pngs, List<int> sizes) {
    assert(pngs.length == sizes.length);
    const headerSize = 6;
    const entrySize = 16;
    var offset = headerSize + entrySize * pngs.length;
    final total = offset + pngs.fold<int>(0, (sum, png) => sum + png.length);
    final out = ByteData(total);
    out
      ..setUint16(0, 0, Endian.little) // reserved
      ..setUint16(2, 1, Endian.little) // type: icon
      ..setUint16(4, pngs.length, Endian.little);
    for (var i = 0; i < pngs.length; i++) {
      final base = headerSize + entrySize * i;
      final edge = sizes[i] >= 256 ? 0 : sizes[i]; // 0 means 256
      out
        ..setUint8(base, edge)
        ..setUint8(base + 1, edge)
        ..setUint8(base + 2, 0) // palette size
        ..setUint8(base + 3, 0) // reserved
        ..setUint16(base + 4, 1, Endian.little) // colour planes
        ..setUint16(base + 6, 32, Endian.little) // bits per pixel
        ..setUint32(base + 8, pngs[i].length, Endian.little)
        ..setUint32(base + 12, offset, Endian.little);
      offset += pngs[i].length;
    }
    final bytes = out.buffer.asUint8List();
    offset = headerSize + entrySize * pngs.length;
    for (final png in pngs) {
      bytes.setRange(offset, offset + png.length, png);
      offset += png.length;
    }
    return bytes;
  }
}
