<#
.SYNOPSIS
  Run one or more real-UI campaigns on the Windows shim checkout INSIDE the
  console session (real OS input), from an SSH session.

.DESCRIPTION
  For each campaign: builds a per-run env file (vcvars for the launcher's
  native rebuild, then the toolchain PATH, TOXEE_PAIR_TCP_ONLY=1 and
  TOXEE_WIN_OS_INPUT=1), then hands the unified runner to
  win_run_interactive.ps1 so it executes in session 1 where AppActivate /
  SendKeys / the clipboard work. Logs land in -LogDir as
  <campaign>-<stamp>.log; a summary line per campaign is printed at the end.
  Campaigns run SEQUENTIALLY (one A/B pair on the VM at a time).

.EXAMPLE
  powershell -ExecutionPolicy Bypass -File tool\vmtest\win_run_campaign.ps1 -Campaigns rui-win-account-settings
  powershell -ExecutionPolicy Bypass -File tool\vmtest\win_run_campaign.ps1 -Campaigns rui-win-os-input,rui-win-relaunch -TimeoutMinutes 120
#>
param(
  [Parameter(Mandatory = $true)] [string[]]$Campaigns,
  [string]$Dst = 'C:\vmtest\toxee-win',
  [string]$LogDir = 'C:\vmtest\logs',
  [string]$VcpkgRoot = 'C:\vcpkg',
  [int]$TimeoutMinutes = 120,
  [string]$Extra = "",
  [switch]$NoOsInput
)
$ErrorActionPreference = "Continue"
# `powershell -File x.ps1 -Campaigns a,b,c` (the SSH form) hands ONE string
# "a,b,c" to a [string[]] parameter — split so both invocation forms work.
$Campaigns = @($Campaigns | ForEach-Object { $_ -split ',' } | Where-Object { $_.Trim() } | ForEach-Object { $_.Trim() })
New-Item -ItemType Directory -Force -Path $LogDir | Out-Null
$vcvars = "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Auxiliary\Build\vcvarsall.bat"
$msvc = Get-ChildItem "C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC" -Directory -ErrorAction SilentlyContinue | Sort-Object Name -Descending | Select-Object -First 1
$arch = if ($env:PROCESSOR_ARCHITECTURE -eq 'ARM64' -and $msvc -and (Test-Path (Join-Path $msvc.FullName 'bin\HostARM64\x64\cl.exe'))) { 'arm64_amd64' } else { 'amd64' }
$nativeRoot = '/' + $Dst.Substring(0, 1).ToLower() + $Dst.Substring(2).Replace('\', '/') + '/build/tim2tox-native'

$results = @()
foreach ($campaign in $Campaigns) {
  $stamp = Get-Date -Format 'yyyyMMdd-HHmmss'
  $log = Join-Path $LogDir "$campaign-$stamp.log"
  $envFile = Join-Path $LogDir "env-$campaign-$stamp.ps1"
  Set-Content -Path $envFile -Value "# generated by win_run_campaign.ps1" -Encoding ascii
  # vcvars FIRST (its PATH is a full replacement) ...
  $vcEnv = & cmd /c "`"$vcvars`" $arch >nul 2>&1 && set"
  foreach ($line in $vcEnv) {
    if ($line -match '^(INCLUDE|LIB|LIBPATH|PATH|VCToolsInstallDir|VCINSTALLDIR|WindowsSdkDir|WindowsSDKVersion|UCRTVersion|UniversalCRTSdkDir)=(.*)$') {
      Add-Content -Path $envFile -Value ("`$env:{0} = '{1}'" -f $matches[1], $matches[2].Replace("'", "''")) -Encoding ascii
    }
  }
  # ... then the toolchain (prepends) + the real-UI knobs.
  @(
    "`$env:CC = 'cl'; `$env:CXX = 'cl'",
    "`$env:PATH = 'C:\Program Files\Git\bin;C:\Program Files\Git\cmd;C:\dev\flutter\bin;C:\Strawberry\c\bin;' + `$env:PATH",
    "`$env:VCPKG_ROOT = '$VcpkgRoot'",
    "`$env:TIM2TOX_WINDOWS_ARCH = 'x64'",
    "`$env:TIM2TOX_NATIVE_BUILD_ROOT = '$nativeRoot'",
    "`$env:MCP_BINDING = 'skill'",
    "`$env:TOXEE_L3_TEST = 'true'",
    "`$env:TOXEE_PAIR_TCP_ONLY = '1'",
    "`$env:TOXEE_REAL_UI_PLATFORM = 'windows'",
    $(if ($NoOsInput) { "Remove-Item Env:\TOXEE_WIN_OS_INPUT -ErrorAction SilentlyContinue" } else { "`$env:TOXEE_WIN_OS_INPUT = '1'" })
  ) | Add-Content -Path $envFile -Encoding ascii

  $cmd = "dart run tool/mcp_test/fixture_c_unified_runner.dart --class=2proc-ui --real-ui-platform=windows --real-ui-campaign=$campaign $Extra"
  Write-Host "[win-campaign] $campaign -> $log"
  # Warm the real-input helper's compiled-assembly cache (first compile of the
# C# runs csc.exe, 10-40 s on the emulated VM — enough to trip the driver's
# per-step timeout on the first foreground of a run).
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $Dst 'tool\mcp_test\win_os_input.ps1') | Out-Null
& powershell -NoProfile -ExecutionPolicy Bypass -File (Join-Path $Dst 'tool\vmtest\win_run_interactive.ps1') `
      -WorkingDirectory $Dst -EnvFile $envFile -LogPath $log -TimeoutMinutes $TimeoutMinutes -TaskName "toxee_rui_$campaign" `
      -Command $cmd
  $rc = $LASTEXITCODE
  Remove-Item $envFile -ErrorAction SilentlyContinue
  $summary = (Select-String -Path $log -Pattern 'real-UI summary:' -ErrorAction SilentlyContinue | Select-Object -Last 1).Line
  $results += ("{0}: exit={1} {2}" -f $campaign, $rc, $summary)
  # Evidence FIRST (the launcher wipes A\ and B\ on every launch, and a failed
  # attempt's app log is otherwise gone before anyone looks): keep each
  # instance's app + stdio logs next to the campaign log, then drop the
  # regenerated app_support trees (disk hygiene).
  foreach ($n in 'A', 'B') {
    $inst = Join-Path $Dst "build\windows_runtime\$n"
    foreach ($f in 'flutter_client.log', 'toxee_stdio.log', 'toxee_stdio.err') {
      $src = Join-Path $inst $f
      if (Test-Path $src) { Copy-Item $src (Join-Path $LogDir "$campaign-$stamp.$n.$f") -ErrorAction SilentlyContinue }
    }
    Remove-Item -Recurse -Force $inst -ErrorAction SilentlyContinue
  }
}
Write-Host "[win-campaign] ===== results ====="
$results | ForEach-Object { Write-Host $_ }
